config/routes.rb
Cartoque::Application.routes.draw do
  resources :postits, except: [:index, :show]
  resources :upgrade_exclusions, except: :show
  resources :components
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :mailing_lists, except: :show
  resources :roles, except: :show do
    collection { post 'sort' }
  end
  resources :datacenters, except: :show
  resources :upgrades, only: [:index, :update] do
    member { put 'validate' }
  end
  resources :companies do
    collection { get 'autocomplete' }
  end
  resources :contacts do
    collection { get 'autocomplete' }
  end
  resources :backup_exclusions, except: :show
  resources :backup_jobs, only: [:index]
  resources :licenses
  resources :cronjobs, only: [:index]
  resources :settings, only: :index do
   collection { put 'update_all', as: 'update_all' }
   collection { get 'edit_visibility'; put 'update_visibility' }
  end
  resources :saas, only: :show
  resources :users, except: :show do
    collection { get 'random_token' }
  end
  resources :physical_racks, except: :show
  resources :sites, except: :show
  resources :operating_systems
  resources :tomcats, only: [:index, :show]
  resources :databases do
    collection { get 'distribution' }
    member { delete 'destroy_instance' }
  end
  resources :storages
  resources :servers do
    collection { get 'maintenance' }
  end
  resources :applications

  Dir.glob(File.expand_path("../../vendor/plugins/*/config/routes.rb",__FILE__)).each do |routefile|
    engine_name = routefile.gsub("/config/routes.rb", "").gsub(%r{.*/vendor/plugins/}, "")
    engine = "#{engine_name.camelize}::Engine".constantize rescue nil
    mount engine => "/#{engine_name}" unless engine.nil?
  end

  put 'hide_announcement' => 'javascripts#hide_announcement', as: 'hide_announcement' 

  get 'puppet(/:action(.:format))', to: 'puppet', as: 'puppet'

  root to: "welcome#index"

  match '*a', to: 'Application#render_404'

end

app/models/physical_rack.rb
class PhysicalRack
  include Mongoid::Document
  include Mongoid::Alize
  include ConfigurationItem

  field :name, type: String
  field :site_name, type: String
  field :status, type: Integer
  #associations
  belongs_to :site
  has_many :servers, dependent: :nullify
  #denormalized fields
  alize :site, :name

  before_destroy :nullify_denormalized_fields

  STATUS_PROD = 1
  STATUS_STOCK = 2

  def full_name
    [site_name, name].compact.join(" - ")
  end
  alias :to_s :full_name

  def stock?
    status == STATUS_STOCK
  end

  def site_name
    site_fields.try(:fetch, 'name') if site_id.present?
  end

  protected
  #TODO: remove it when https://github.com/logandk/mongoid_denormalize/pull/10 is merged and released
  def nullify_denormalized_fields
    servers.each do |server|
      server.update_attribute(:physical_rack_id, nil)
    end
  end
end

app/controllers/physical_racks_controller.rb
class PhysicalRacksController < InheritedResources::Base
  layout "admin"

  before_filter :count_servers_per_rack, only: :index

  def create
    create! { physical_racks_url }
  end

  def update
    update! { physical_racks_url }
  end

  protected
  def collection
    @physical_racks ||= end_of_association_chain.order_by([[:status, :asc], [:site_name, :asc], [:name, :asc]])
  end

  def count_servers_per_rack
    @servers_count = Server.where(virtual: false).group_by(&:physical_rack_id)
                           .inject({}) { |memo,(k,v)| memo[k.to_s] = v.count; memo }
  end
end

app/views/physical_racks/_form.html.erb
<div class="span5 center">

<%= simple_form_for(@physical_rack) do |f| %>
  <%= action_links do %>
    <%= f.button :submit, class: "btn btn-primary" %>
    <%= t(:or) %> <%= link_to t(:back_to_the_list), physical_racks_path %>
  <% end %>

  <table class="show_item">
    <tbody>
      <%= tabular_errors @physical_rack %>
      <%= f.input :name, required: true, wrapper_class: "th" %>
      <%= f.input :site_id, :collection => Site.all %>
      <%= f.input :status, as: :select, include_blank: false,
                           collection: [[t(:rack_real),  PhysicalRack::STATUS_PROD],
                                           [t(:rack_stock), PhysicalRack::STATUS_STOCK]] %>
    </tbody>
  </table>
<% end %>

</div>

app/views/physical_racks/edit.html.erb
<% title t(:edit_a_physical_rack) %>

<%= render 'form' %>

<div class="span4 physical_rack_servers">
  <h3><%= t(:servers) %></h3>
  <ul class="comparison details">
    <%= @physical_rack.servers.sort_by(&:name).map{|s| content_tag(:li, link_to(s, s))}.join.html_safe %>
  </ul>
</div>

app/views/physical_racks/index.html.erb
<% title t(:physical_racks) %>

<div class="span9 center">

<%= action_links do %>
  <%= link_to t(:new_physical_rack), new_physical_rack_path %>
<% end %>

<table class="pretty list physical_racks">
<thead>
  <tr>
    <th><%= t(:site) %></th>
    <th><%= t(:name) %></th>
    <th><%= t(:servers) %></th>
    <th><%= t(:stock) %>?</th>
    <th></th>
  </tr>
</thead>
<tbody class="long-list">
<% @physical_racks.each do |physical_rack| %>
  <tr>
    <td><%= physical_rack.site_name %></td>
    <td><%= link_to physical_rack.name, edit_physical_rack_path(physical_rack) %></td>
    <td class="center"><%= @servers_count[physical_rack.id.to_s] || 0 %></td>
    <td class="stock center"><%= "&#149;".html_safe if physical_rack.stock? %></td>
    <td><%= link_to_delete physical_rack %></td>
  </tr>
<% end %>
<% if @servers_count[nil] %>
  <tr>
    <td colspan="2"><em><%= t(:unknown) %></em></td>
    <td class="center"><%= @servers_count[nil] %></td>
    <td></td>
    <td></td>
  </tr>
<% end %>
</tbody>
</table>

</div>

app/views/physical_racks/new.html.erb
<% title t(:new_physical_rack) %>

<%= render 'form' %>