config/routes.rb
Cartoque::Application.routes.draw do
  resources :postits, except: [:index, :show]
  resources :upgrade_exclusions, except: :show
  resources :components
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :mailing_lists, except: :show
  resources :roles, except: :show do
    collection { post 'sort' }
  end
  resources :datacenters, except: :show
  resources :upgrades, only: [:index, :update] do
    member { put 'validate' }
  end
  resources :companies do
    collection { get 'autocomplete' }
  end
  resources :contacts do
    collection { get 'autocomplete' }
  end
  resources :backup_exclusions, except: :show
  resources :backup_jobs, only: [:index]
  resources :licenses
  resources :cronjobs, only: [:index]
  resources :settings, only: :index do
   collection { put 'update_all', as: 'update_all' }
   collection { get 'edit_visibility'; put 'update_visibility' }
  end
  resources :saas, only: :show
  resources :users, except: :show do
    collection { get 'random_token' }
  end
  resources :physical_racks, except: :show
  resources :sites, except: :show
  resources :operating_systems
  resources :tomcats, only: [:index, :show]
  resources :databases do
    collection { get 'distribution' }
    member { delete 'destroy_instance' }
  end
  resources :storages
  resources :servers do
    collection { get 'maintenance' }
  end
  resources :applications

  Dir.glob(File.expand_path("../../vendor/plugins/*/config/routes.rb",__FILE__)).each do |routefile|
    engine_name = routefile.gsub("/config/routes.rb", "").gsub(%r{.*/vendor/plugins/}, "")
    engine = "#{engine_name.camelize}::Engine".constantize rescue nil
    mount engine => "/#{engine_name}" unless engine.nil?
  end

  put 'hide_announcement' => 'javascripts#hide_announcement', as: 'hide_announcement' 

  get 'puppet(/:action(.:format))', to: 'puppet', as: 'puppet'

  root to: "welcome#index"

  match '*a', to: 'Application#render_404'

end

app/models/operating_system.rb
class OperatingSystem
  include Mongoid::Document
  include Mongoid::Ancestry
  include Mongoid::Alize
  include Mongoid::Timestamps

  #standard fields
  field :name, type: String
  field :codename, type: String
  field :managed_with_puppet, type: Boolean
  #associations
  has_ancestry cache_depth: true
  has_many :servers, dependent: :nullify

  validates_presence_of :name

  #doesn't work with Ancestry (see: https://github.com/stefankroes/ancestry/issues/42)
  #default_scope order('name')

  def to_s
    name + (codename.present? ? " "+codename : "")
  end
end

app/controllers/operating_systems_controller.rb
class OperatingSystemsController < InheritedResources::Base
  respond_to :html, :js
  respond_to :json, only: [:index, :show]

  layout "admin"

  def index
    if "#{params[:format]}" == "json"
      @operating_systems = OperatingSystem.all.order_by(:name.asc)
    else
      @operating_systems = OperatingSystem.arrange(order: [:name, :asc])
      @os_servers_count = Server.all.group_by(&:operating_system_id)
                                    .inject({}) { |memo,(k,v)| memo[k.to_s] = v.count; memo }
      @os_servers_count.default = 0
      if params[:graph_subtree]
        @root_os = OperatingSystem.find(params[:graph_subtree].to_s)
        @os_subtree = @root_os.descendants.arrange(order: [:name, :asc]) if @root_os.present?
      else
        @os_subtree = @operating_systems
      end
      @last_updated_server = Server.order_by(:updated_at.desc).first
      @last_updated_system = OperatingSystem.order_by(:updated_at.desc).first
    end
  end

  def create
    create! { operating_systems_url }
  end

  def update
    update! { operating_systems_url }
  end
end

app/helpers/operating_systems_helper.rb
module OperatingSystemsHelper
  def render_operating_system(operating_system)
    img = ""
    icon_path = operating_system.icon_path.gsub("images/","")
    if File.file?(Rails.root.join("public","images",icon_path))
      img << image_tag(icon_path, size: "12x12", class: "os-icon")
    else
      img << image_tag("blank.gif", size: "12x12", class: "os-icon")
    end
    img.html_safe + operating_system.name
  end

  def nested_operating_systems(operating_systems)
    operating_systems.map do |operating_system, sub_os|
      subtree_ids = [operating_system.id] + descendant_ids(sub_os)
      render(operating_system, subtree: subtree_ids) + nested_operating_systems(sub_os)
    end.join.html_safe
  end

  def descendant_ids(sub_os)
    sub_os.inject([]) do |memo,subset|
      memo << subset.first.id #key os
      memo += descendant_ids(subset.last) #children
      memo
    end
  end
end

app/views/operating_systems/_form.html.erb
<div class="span9 center">

<%= simple_form_for(@operating_system) do |f| %>
  <%= action_links do %>
    <%= f.button :submit, class: "btn btn-primary" %>
    <%= t(:or) %> <%= link_to t(:back_to_the_list), operating_systems_path %>
  <% end %>

  <table class="inputs">
    <tbody>
      <%= tabular_errors @operating_system %>
      <%= f.input :name, required: true, wrapper_class: 'th' %>
      <%= f.input :codename %>
      <%= f.input :managed_with_puppet, as: :boolean %>
      <% @os = OperatingSystem.scoped.arrange(order: :name.asc) %>
      <% exclusions_for_future_versions = @operating_system.subtree unless @operating_system.blank? || @operating_system.new_record? %>
      <%= f.input :parent_id, as: :select, collection: ancestry_options(@os){|i| "#{'-'*i.depth} #{i.name}"} %>
    </tbody>
  </table>
<% end %>

</div>

app/views/operating_systems/_operating_system.html.erb
<% total_servers = subtree.inject(0){|sum, descendant| sum + @os_servers_count[descendant.to_s] } %>
<%= content_tag_for :div, operating_system do %>
  <div class="contextual">
    <%= link_to_delete operating_system %>
  </div>
  <div class="contextual servers-count">
    <%= @os_servers_count[operating_system.id.to_s] %>
  </div>
  <%= content_tag :div, style:"padding-left:#{15 * operating_system.depth - 10}px" do %>
    <%= link_to operating_system.to_s, edit_operating_system_path(operating_system), class: (operating_system.depth > 0 ? "nested-os" : nil) %>
    <span class="tiny">(<%= total_servers %>)</span>
    <% if operating_system.managed_with_puppet? %>
      <span class="tiny puppet">P</span>
    <% end %>
  <% end %>
  <script type="text/javascript">
    serversmap['<%= operating_system.id %>'] = <%= total_servers %>;
  </script>
<% end %>

app/views/operating_systems/edit.html.erb
<% title "#{t(:operating_system)}: #{@operating_system}" %>

<%= render 'form' %>

app/views/operating_systems/index.html.erb
<% title t(:operating_systems) %>

<% cache [@last_updated_system, @last_updated_server] do %>

<div id="operating_systems" class="span5 center">
  
<%= action_links do %>
  <%= link_to t(:new_operating_system), new_operating_system_path %>
<% end %>

<script type="text/javascript"> 
  var serversmap = new Object;
</script>

<table class="list operating_systems">
  <tr>
    <th>
      <div class="contextual"><%= t(:servers) %></div>
      <%= "#{t(:name)}(#{t(:total)})" %>
    </th>
  </tr>
  <tr>
    <td>
      <%= nested_operating_systems @operating_systems %>
    </td>
  </tr>
</table>

</div>
<% end %><!-- end caching ; we cannot cache graphs below cause they're somehow dynamic -->

<div class="span4 center">
<% if @os_subtree.present? %>
  <div class="graph-links tiny">
  <% if @root_os.present? %>
    <%= link_to(@root_os.parent.present? ? "#{t(:center_on)} #{@root_os.parent}" : t(:center), operating_systems_path(graph_subtree: @root_os.parent_id)) %>
  <% else %>
    &nbsp;
  <% end %>
  </div>
  <div class="graph-container">
    <script type="text/javascript" charset="utf-8"> 
      window.onload = function () {
        var r = Raphael("distribution", 300, 410);
        r.g.txtattr.font = "12px 'Fontin Sans', Fontin-Sans, sans-serif";

        var title = "<%= t(:systems_distribution) %>";
      <% if @root_os.present? %>
        title += " <%= @root_os.to_s %>";
      <% end %>
        r.g.text(150, 25, title).attr({"font-size": 16});

        var subtree = [];
        <% @os_subtree.each do |os,subos| %>
        subtree.push({ value: serversmap['<%= os.id %>'], legend: "<%= %(%% #{os} [#{os.id}]) %>",
                       href: "<%= subos.any? ? operating_systems_path(graph_subtree: os.id) : "" %>" });
        <% end %>
        subtree.sort(function(a,b){return b.value - a.value});
        var pie = r.g.piechart(150, 155, 100, $.map(subtree, function(os,i){ return os.value}),
                    { legend: $.map(subtree, function(os,i){ return os.legend}), legendmark: "disc", legendpos: "south", 
                      href: $.map(subtree, function(os,i){ return os.href}), colors: ["#57f", "#5c5", "#f83", "#d49", "#fc4", "#f55"] });

        var legend_regex = /(.+) \[(\w+)\]$/;
        $.each(pie.labels, function() {
          var label = this[1].attrs.text;
          this.osId = label.replace(legend_regex, "$2");
          this[1].attr({text: label.replace(legend_regex, "$1")});
        });
        pie.hover(function () {
          this.sector.stop();
          this.sector.scale(1.05, 1.05, this.cx, this.cy);
          if (this.label) {
            this.label[0].stop();
            this.label[0].scale(1.2);
            this.label[1].attr({"font-weight": 800});
            var sel = "#operating_system_"+this.label.osId
            //sel += ", #nested_os_"+this.label.osId+" .operating_system"
            $(sel).addClass("hover");
          }
        }, function () {
          this.sector.animate({scale: [1, 1, this.cx, this.cy]}, 500, "bounce");
          if (this.label) {
            this.label[0].animate({scale: 1}, 500, "bounce");
            this.label[1].attr({"font-weight": 400});
            var sel = "#operating_system_"+this.label.osId
            //sel += ", #nested_os_"+this.label.osId+" .operating_system"
            $(sel).removeClass("hover");
          }
        });
      };
    </script>
    <div id="distribution" class="graph" style="width:300px;"></div>
  </div>
<% end %>
</div>

app/views/operating_systems/new.html.erb
<% title t(:new_operating_system) %>

<%= render 'form' %>