config/routes.rb
Cartoque::Application.routes.draw do
  resources :postits, except: [:index, :show]
  resources :upgrade_exclusions, except: :show
  resources :components
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :mailing_lists, except: :show
  resources :roles, except: :show do
    collection { post 'sort' }
  end
  resources :datacenters, except: :show
  resources :upgrades, only: [:index, :update] do
    member { put 'validate' }
  end
  resources :companies do
    collection { get 'autocomplete' }
  end
  resources :contacts do
    collection { get 'autocomplete' }
  end
  resources :backup_exclusions, except: :show
  resources :backup_jobs, only: [:index]
  resources :licenses
  resources :cronjobs, only: [:index]
  resources :settings, only: :index do
   collection { put 'update_all', as: 'update_all' }
   collection { get 'edit_visibility'; put 'update_visibility' }
  end
  resources :saas, only: :show
  resources :users, except: :show do
    collection { get 'random_token' }
  end
  resources :physical_racks, except: :show
  resources :sites, except: :show
  resources :operating_systems
  resources :tomcats, only: [:index, :show]
  resources :databases do
    collection { get 'distribution' }
    member { delete 'destroy_instance' }
  end
  resources :storages
  resources :servers do
    collection { get 'maintenance' }
  end
  resources :applications

  Dir.glob(File.expand_path("../../vendor/plugins/*/config/routes.rb",__FILE__)).each do |routefile|
    engine_name = routefile.gsub("/config/routes.rb", "").gsub(%r{.*/vendor/plugins/}, "")
    engine = "#{engine_name.camelize}::Engine".constantize rescue nil
    mount engine => "/#{engine_name}" unless engine.nil?
  end

  put 'hide_announcement' => 'javascripts#hide_announcement', as: 'hide_announcement' 

  get 'puppet(/:action(.:format))', to: 'puppet', as: 'puppet'

  root to: "welcome#index"

  match '*a', to: 'Application#render_404'

end

app/models/application.rb
class Application
  include Mongoid::Document
  include Mongoid::Alize
  include Mongoid::Timestamps
  include Mongoid::Slug
  include ConfigurationItem
    
  #standard fields
  field :name, type: String
  field :description, type: String
  field :ci_identifier, type: String
  #associations
  has_many :application_instances, autosave: true, dependent: :destroy
  has_many :relationships, as: :item, dependent: :destroy
  #slug
  slug :name do |application|
    application.name
               .downcase
               .gsub(/[^a-z0-9_-]/,"-")
               .gsub(/--+/, "-")
               .gsub(/^-|-$/,"")
  end

  validates_presence_of :name
  validates_associated :application_instances

  accepts_nested_attributes_for :application_instances, allow_destroy: true,
                                reject_if: lambda{|a| a[:name].blank? && !a[:server_ids].detect(&:present?) }

  def relationships_map
    map = relationships.group_by do |relation|
      relation.role_id.to_s
    end
    map.default = []
    map
  end

  def relationships_map=(map)
    relationships = Role.all.map do |role|
      rel = Relationship.find_or_initialize_by(role_id: role.id, item_type: self.class, item_id: self.id)
      rel.contact_ids = Array(map[role.id.to_s].try(:split, ","))
      rel.save
    end
  end

  def contacts_with_role(role)
    #TODO: be sure we have only one relationship per role, then use Enumerable#detect()
    relationships_map[role.id.to_s].map(&:contacts).flatten
  end

  def to_s
    name
  end

  def sorted_application_instances
    ary = application_instances
    prod = ary.select{|ai| ai.name == "prod"}
    preprod = ary.select{|ai| ai.name == "preprod"}
    ecole = ary.select{|ai| ai.name == "ecole"}
    others = ary.select{|ai| !ai.name.in? %w(prod preprod ecole) }
    [prod, ecole, preprod, others].flatten.compact
  end

  def self.dokuwiki_dir
    File.expand_path("data/dokuwiki", Rails.root)
  end

  def dokuwiki_pages
    keywords = [name] + application_instances.map(&:application_urls).flatten.map(&:url)
    keywords.map!{|k| k.gsub(%r{^\s*\S+://}, "").gsub(%r{/.*}, "").downcase}
    available_docs = Dir.glob("#{Application.dokuwiki_dir}/*.txt").map do |f|
      File.readlines(f).map(&:chomp)
    end.flatten
    docs = []
    keywords.each do |kw|
      docs += available_docs.select do |docname|
        docname.include?(kw)
      end.map do |doc|
        doc.gsub(/\.txt$/,"").gsub("/", ":")
      end
    end
    docs.uniq
  end

  class << self
    def find(*args)
      where(ci_identifier: args.first).first || where(slug: args.first).first || super
    end

    def search(term)
      if term
        where(name: Regexp.mask(term))
      else
        all
      end
    end
  end
end

app/models/exclusion.rb
class Exclusion
  include Mongoid::Document
  include Mongoid::Timestamps

  field :reason, type: String
  field :type, type: String
  belongs_to :user
  has_and_belongs_to_many :servers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :seek_authentication_token
  before_filter :authenticate_user!
  before_filter :set_format
  before_filter :set_locale
  around_filter :scope_current_user

  protect_from_forgery

  # Save user from seeing exceptions when trying to retrieve an undefined Mongoid object
  rescue_from Mongoid::Errors::DocumentNotFound, Moped::Errors::InvalidObjectId, with: :render_404
  def render_404(exception = nil)
    logger.debug "Rendering 404 with exception: #{exception.message}" if exception
    respond_to do |format|
      format.html { render text: %(<div class="center not_found">These are not the droids you're looking for</div>),
                           status: :not_found, layout: true }
      format.any(:atom, :xml, :js, :json) { head :not_found }
    end
  end

  # This filter allows authentication from a custom http header
  private
  def seek_authentication_token
    params[:api_token] ||= env["HTTP_X_API_TOKEN"]
  end

  #for more information on pdfkit + asset pipeline:
  #http://www.mobalean.com/blog/2011/08/02/pdf-generation-and-heroku
  def request_from_pdfkit?
    request.env["Rack-Middleware-PDFKit"] == "true"
  end
  helper_method :request_from_pdfkit?

  # locale selection
  # see: http://guides.rubyonrails.org/i18n.html
  def set_locale
    #logger.debug "* Current user: #{current_user.inspect}"
    #logger.debug "* Accept-Language: #{request.env['HTTP_ACCEPT_LANGUAGE']}"
    locale_candidate = current_user.try(:locale).presence
    locale_candidate ||= extract_locale_from_accept_language_header
    if locale_candidate && I18n.available_locales.include?(locale_candidate.to_sym)
      I18n.locale = locale_candidate
    end
    #logger.debug "* Locale set to '#{I18n.locale}'"
  end

  # keeps good format accross request for API calls
  def set_format
    request.format = :json if params[:api_token].present? && params[:format].blank?
  end

  def scope_current_user
    User.current = current_user
    yield
  ensure
    User.current = nil
  end

  def extract_locale_from_accept_language_header
    "#{request.env['HTTP_ACCEPT_LANGUAGE']}".scan(/^[a-z]{2}/).first
  end

  #https://github.com/plataformatec/devise/wiki/How-To:-redirect-to-a-specific-page-on-successful-sign-in
  def after_sign_in_path_for(resource)
    #return request.env['omniauth.origin'] || stored_location_for(resource) || root_path
    #=> with our setup, omniauth.origin always contain sign_in page since user was first redirected on it
    return stored_location_for(resource) || root_path
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ResourcesController
  include SortHelpers

  respond_to :html, :js, :xml
  respond_to :json, only: [:index, :show]

  helper_method :sort_column, :sort_direction

  def show
    super do |format|
      format.xml do
        render xml: @application.to_xml(include: { application_instances: { include: [:servers, :application_urls] } },
                                           methods: :dokuwiki_pages)
      end
    end
  end

  def collection
    @applications ||= end_of_association_chain.search(params[:search]).order_by(mongo_sort_option)
                                              .paginate(:page => params[:page], :per_page => WillPaginate.per_page)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Storcs::Formatter

  def sortable(column, title = nil)
    title ||= t(column, default: column.titleize)
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(sort: column, direction: direction)
  end

  def sortable_css_class(column)
    column == sort_column ? "current #{sort_direction}" : "sortable"
  end

  def sortable_th(column, title = nil, html_options = {})
    content_tag :th, {class: sortable_css_class(column)}.merge(html_options) do
      sortable(column,title)
    end
  end

  def sortable_link(column, title = nil)
    title ||= t(column, default: column.titleize)
    content_tag :span, class: sortable_css_class(column) do
      sortable(column, title) + content_tag(:span, "", class:"arrow")
    end
  end

  def hidden_sort_fields
    hidden_field_tag(:direction, params[:direction]) +
      hidden_field_tag(:sort, params[:sort])
  end

  def hidden_controller_scopes_fields
    (controller.scopes_configuration || {}).keys.map{|scope| hidden_field_tag scope, params[scope]}.inject(:+)
  end

  def progress_bar(pcts, options={})
    #width
    width = 120
    if options[:width].present? && options[:width].is_a?(Integer)
      width = options[:width]
    end
    width = width.to_f
    #percents calculations
    pcts = [pcts, pcts] unless pcts.is_a?(Array)
    pcts = pcts.collect(&:round)
    pcts[1] = pcts[1] - pcts[0]
    pcts.map! do |pct|
      pct * width / 100
    end
    pcts << (width - pcts[1] - pcts[0])
    legend = options[:legend] || ''
    o = %(<table class="progress" style="width:#{width + 30}px;"><tr>)
    o << %(<td class="closed" style="width:#{pcts[0]}px;"></td>) if pcts[0] > 0
    o << %(<td class="done" style="width:#{pcts[1]}px;"></td>) if pcts[1] > 0
    o << %(<td class="todo" style="width:#{pcts[2]}px;"></td>) if pcts[2] > 0
    o << %(<td class="legend" style="width:30px">#{legend}</td>)
    o << %(</tr></table>)
    o.html_safe
  end

  def sidebar_item(title, url, num = nil)
    css = request && request.path && request.path.include?(url) ? "active" : nil
    content = "".html_safe
    content << content_tag(:div, num, class: "contextual") if num
    content << link_to(title, url)
    content_tag :li, content, class: css
  end

  def show_version
    link_to("Cartoque", "http://jbbarth.github.com/cartoque/", target: "_blank") + " v#{Cartoque::VERSION}"
  end

  # see ancestry wiki on github
  # usage: <%= f.select :parent_id, @categories %>
  #
  # @categories = ancestry_options(Category.scoped.arrange(order: 'name'){|i| "#{'-'*i.depth} #{i.name}"})
  def ancestry_options(items, &block)
    result = []
    items.map do |item, sub_items|
      result << [ yield(item), item.id ]
      #recursive call
      result += ancestry_options(sub_items) {|i| "#{'-'*i.depth} #{i.name}" }
    end
    result
  end

  def tabular_errors(object)
    if object.errors.any?
      html = <<-EOF
      <tr id="error_explanation"><td colspan="2">
        <h2>#{pluralize(object.errors.count, "erreur")} :</h2>
        <ul>
        #{object.errors.map do |key,msg|
            "<li>&#171; #{t(key, default: key)} &#187; #{msg}</li>"
          end.join(" ")}
        </ul>
      </td></tr>
      EOF
      html.html_safe
    end
  end

  def action_links(&block)
    content_tag(:div, class: "actions navbar navbar-static") do
      capture(&block)
    end
  end

  def links_for(application)
    html = ""
    if application.ci_identifier.present?
      html << link_to("R", "#{redmine_url}/projects/#{application.ci_identifier}",
                      title: "Redmine #{application.ci_identifier}", class: "item-badge link-to-redmine")
    end
    content_tag(:span, html.html_safe, class: "links")
  end

  def redmine_url
    @redmine_url ||= Setting.redmine_url
  end

  def context_li(text, url, options = {})
    current = options.delete(:current)
    if current
      content_tag :li, content_tag(:span, text, class: "current")
    else
      content_tag :li, link_to(text, url, options)
    end
  end

  # extracted from Rails source since link_to_javascript will be removed in Rails 4.0
  # TODO: extract occurences in clean, unobstrusive javascript
  def link_to_javascript(name, *args, &block)
    html_options = args.extract_options!.symbolize_keys

    function = block_given? ? update_page(&block) : args[0] || ''
    onclick = "#{"#{html_options[:onclick]}; " if html_options[:onclick]}#{function}; return false;"
    href = html_options[:href] || '#'

    content_tag(:a, name, html_options.merge(:href => href, :onclick => onclick))
  end

  def link_to_servername(name)
    link_to name, server_path(Server.identifier_for(name)), class: "server"
  end

  def link_to_server_if_exists(name)
    s = Server.where(name: name).first
    s ? link_to(name, s, class: "server") : server_missing(name)
  end

  def server_missing(name)
    name + " " + link_to("+", new_server_path(server: { name: name }),
                         class: "action create-server",
                         title: t(:"helpers.submit.create"))
  end

  def link_to_rack(rack_name, rack_id)
    return "" if rack_name.blank?
    link_to rack_name, servers_path(by_location: "rack-#{rack_id}")
  end

  def link_to_remove_fields(name, f, options = {})
    if options.delete(:confirm)
      js = "if (confirm('#{t(:text_are_you_sure)}')) remove_fields(this)"
    else
      js = "remove_fields(this)"
    end
    f.hidden_field(:_destroy) + link_to_javascript(name, js, {class: "link-delete"}.merge(options)).html_safe
  end

  def link_to_add_fields(name, f, association, extra_params = {})
    new_object = (extra_params.delete(:klass) || f.object.class.reflect_on_association(association).klass).new
    fields = f.fields_for(association, new_object, child_index: "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", {f: builder}.merge(extra_params))
    end
    link_to_javascript(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")", class: "link-add")
  end

  def link_to_edit(path)
    link_to image_tag("edit.png", size: "16x16", class: "action"), path
  end

  def link_to_delete(resource, url = nil)
    confirmation = resource.respond_to?(:name) ? t(:text_confirm_delete, element: resource.name) : t(:text_are_you_sure)
    link_to image_tag("delete.png", size: "16x16", class: "action"), url || resource,
            method: :delete, title: "Delete #{resource.class.name.parameterize} #{resource.to_param}",
            data: { confirm: confirmation }
  end

  def current_announcement
    return @current_announcement if defined?(@current_announcement)
    hide_time = current_user.settings["announcement_hide_time"]
    if hide_time
      if Setting.site_announcement_updated_at && Setting.site_announcement_updated_at > hide_time
        @current_announcement = Setting.site_announcement_message
      else
        @current_announcement = nil
      end
    else
      @current_announcement = Setting.site_announcement_message
    end
    @current_announcement
  end

  def link_to_website(website)
    website.strip!
    target = website
    target = "http://"+target unless target.match(%r(^\w+://))
    link_to website, target
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
  def collection_for_authentication_methods
    ApplicationInstance::AVAILABLE_AUTHENTICATION_METHODS.map do |meth|
      [ t("auth.#{meth}"), meth ]
    end
  end

  def link_to_doc(doc)
    site = "http://dokuwiki.application.ac.centre-serveur.i2"
    link_to doc.gsub("documentation_generale:",""), "#{site}/doku.php?id=#{doc}", class: "icon icon-url"
  end
end

app/views/applications/_application_instance_fields.html.erb
<table class="fields instance-fields full">
  <tr>
    <td class="label"><%= f.label :name, class: "input" %></td>
    <td>
      <%= f.text_field :name, style: "width:5em; font-weight:bold;" %>
      <%= link_to_remove_fields image_tag("delete.png", size: "16x16")+t(:delete_this_application_instance), f, confirm: true %>
    </td>
  </tr>
  <tr>
    <td class="label"><%= f.label :authentication_method, class: "input" %></td>
    <td>
      <%= f.input_field :authentication_method, as: :select, collection: collection_for_authentication_methods, include_blank: false %>
    </td>
  </tr>
  <tr>
    <td class="label"><%= f.label :application_urls, class: "input" %></td>
    <td>
      <%= f.simple_fields_for :application_urls do |url_form| %>
        <%= render 'application_url_fields', f: url_form %>
      <% end %>
      <span class="add-field"><%= link_to_add_fields image_tag("new_button.png", size: "14x15", class:"inline")+t(:add).downcase, f, :application_urls %></span>
    </td>
  </tr>
  <tr>
    <td class="label"><%= f.label :servers, class: "input" %></td>
    <td class="multiselect">
      <%= f.input_field :server_ids, collection: Server.active.order_by(:name.asc), as: :multiselect %>
    </td>
  </tr>
</table>

app/views/applications/_application_url_fields.html.erb
<div class="fields">
  <%= f.text_field :url, style: "width:22em;" %>
  <%= f.input_field :public, as: :select, collection: [[t(:public_url),true], [t(:private_url),false]], include_blank: false %>
  <%= link_to_remove_fields image_tag("delete.png", size: "16x16"), f %>
</div>

app/views/applications/_form.html.erb
<%= simple_form_for(@application) do |f| %>

  <%= action_links do %>
    <%= f.button :submit, class: "btn btn-primary" %>
    <%= t(:or) %> <%= link_to t(:back_to_the_list), applications_path %>
    <% unless @application.new_record? %>
      | <%= link_to t(:show), @application %>
    <% end %>
  <% end %>

  <div id="application_general" class="span6">
  <table class="inputs full">
    <tbody>
      <%= tabular_errors @application %>
      <%= f.input :name, required: true, wrapper_class: "th", input_html: { style: "width:9em;" } %>
      <%= f.input :description, as: :text, input_html: { size: "48x4" } %>
      <%= f.input :ci_identifier %>
      <!--
      <tr class="input select optional">
        <td class="label">
          <label class="select optional" for="application_contacts"><%= t(:contacts) %></label>
        </td>
        <td class="multiselect">
          <% Role.all.each do |role| %>
            <div class="control-label" style="margin-top:6px;"><%= role.name %></div>
            <%= text_field_tag "application[relationships_map][#{role.id}]", nil, class: "token-input-select",
                               data: { update_url: autocomplete_contacts_path,
                                       pre_populate: @application.contacts_with_role(role).map{|c| {id: c.id, name: c.full_name} } } %>
          <% end %>
        </td>
      </tr>
      -->
    </tbody>
  </table>
  </div>


  <div id="application_instances" class="span6">
  <table class="inputs full">
    <thead>
      <tr>
        <th colspan="2"><%= t(:application_instances) %></th>
      </tr>
    </thead>
    <tbody>
      <tr class="input string optional">
        <td class="content instance-forms" colspan="2">
          <% f.object.application_instances << ApplicationInstance.new if f.object.application_instances.none? %>
          <%= f.simple_fields_for :application_instances, f.object.sorted_application_instances do |instance_form| %>
            <%= render 'application_instance_fields', f: instance_form %>
          <% end %>
          <p class="add-field">
          <%= link_to_add_fields image_tag("new_button.png", size: "14x15", class:"inline")+t(:add_an_application_instance).downcase, f,
                                 :application_instances, klass: ApplicationInstance %>
          </p>
        </td>
      </tr>
    </tbody>
  </table>
  </div>

<% end %>

app/views/applications/_instance.html.erb
<%= content_tag_for :div, instance do %>
  <span class="label"><%= instance.name %></span>
  <ul class="details">
  <% instance.application_urls.where(public: true).sort_by(&:url).each do |app_url| %>
    <li class="application_url"><%= link_to app_url.url, app_url.url, class: "image-url" %></li>
  <% end %>
  <% if instance.servers.any?(&:active?) %>
    <li class="application_instance_servers">
      <%= instance.servers.select(&:active?).sort_by(&:name).map{|server| link_to server.name, server, class: "nocut image-server" }.join(" ").html_safe %>
    </li>
  <% end %>
  </ul>
<% end %>

app/views/applications/_list.html.erb
<tr class="fix-on-scroll">
  <%= sortable_th "name", nil, style: "width:15em" %>
  <th><%= t(:description) %></th>
</tr>
<% for application in @applications %>
  <% cache ["list", application] do %>
    <tr class="has-opaques">
      <td>
        <div class="contextual opaque">
          <%= links_for application %>
          <%= link_to_delete application %>
        </div>
        <%= link_to application.name, application %>
      </td>
      <td><%= application.description %></td>
    </tr>
  <% end %>
<% end %>

app/views/applications/edit.html.erb
<% title t(:edit_an_application) %>

<%= render 'form' %>

app/views/applications/index.html.erb
<% title t(:applications) %>

<div id="applications" class="span12 items_list">

<%= action_links do %>
  <div class="contextual">
    <%= link_to image_tag("file_extension_pdf.png", size: "16x16"), applications_path(params.merge(format: "pdf")) %>
  </div>
  <%= link_to t(:add_an_application), new_application_path %>
<% end %>

<table class="pretty list center">
  <%= form_tag applications_path(params), id: "filters", method: :get do -%>
    <%= hidden_sort_fields %>
    <% (controller.scopes_configuration || {}).keys.each do |scope| %>
      <%= hidden_field_tag scope, params[scope] %>
    <% end %>
  <tr class="filters fixed-size">
    <td><%= text_field_tag "search", params[:search] %></td>
    <td><span id="applications_counter" class="counter"><%= @applications.count %></span></td>
  </tr>
  <% end %>

  <tbody id="applications_list" class="long-list">
    <%= render 'list' %>
  </tbody>
</table>

<%= will_paginate @applications, inner_window: 2, outer_window: 1 %>

</div>

app/views/applications/index.js.erb
$('input[type="hidden"]#sort').attr("value","<%= escape_javascript(sort_column) %>");
$('input[type="hidden"]#direction').attr("value","<%= escape_javascript(sort_direction) %>");
$("#applications_list").html("<%= escape_javascript(render("list")) %>");
$("#applications_counter").html("<%= @applications.count %>");
fixTableHeaders();
$("html, body").animate({ scrollTop: 0 }, 200);

app/views/applications/new.html.erb
<% title t(:new_application) %>

<%= render 'form' %>

app/views/applications/show.html.erb
<% title link_to(t(:applications), applications_path) + " &rsaquo; ".html_safe + @application.name %>

<div class="span8">
  <div id="application-card" class="item-card">
    <div class="item-title">
      <div class="contextual">
        <%= links_for @application %>
      </div>
      <%= @application.title %>
    </div>

    <div class="item-informations server-informations">
      <div class="action-links">
        <%= link_to_edit edit_application_path(@application) %>
        <%= link_to_delete @application %>
      </div>
      <%= @application.description_if_present %>

      <div class="item-details">
        <%= details_box :application_instances, style: "width:60%" do %>
          <%= render partial: 'instance', collection: @application.sorted_application_instances.compact %>
        <% end %>

        <!--
        <%= details_box :contacts, style: "width:36%" do %>
          <% Role.all.each do |role| %>
            <% contacts = @application.contacts_with_role(role) %>
            <% next if contacts.blank? %>
            <span class="label"><%= role.name %></span>
            <ol class="contacts">
              <% contacts.each do |contact| %>
                <li><%= ContactDecorator.new(contact).to_html(:long_form) %></li>
              <% end %>
            </ol>
          <% end %>
        <% end %>
        -->
      </div>
    </div>
  </div>
</div>

<div class="span4 show">
  <% docs = @application.dokuwiki_pages %>
  <div class="related-ci related-documentation-pages">
    <div class="informations">
      <h3>Dokuwiki</h3>
      <% if docs.any? %>
        <ul class="details">
          <% docs.each do |doc| %>
            <li class="application_doc"><%= link_to_doc doc %></li>
          <% end %>
        </ul>
      <% else %>
        <%= t(:no_documentation_page_found) %>.
      <% end %>
    </div>
  </div>
</div>