config/routes.rb
Cartoque::Application.routes.draw do
  resources :postits, except: [:index, :show]
  resources :upgrade_exclusions, except: :show
  resources :components
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :mailing_lists, except: :show
  resources :roles, except: :show do
    collection { post 'sort' }
  end
  resources :datacenters, except: :show
  resources :upgrades, only: [:index, :update] do
    member { put 'validate' }
  end
  resources :companies do
    collection { get 'autocomplete' }
  end
  resources :contacts do
    collection { get 'autocomplete' }
  end
  resources :backup_exclusions, except: :show
  resources :backup_jobs, only: [:index]
  resources :licenses
  resources :cronjobs, only: [:index]
  resources :settings, only: :index do
   collection { put 'update_all', as: 'update_all' }
   collection { get 'edit_visibility'; put 'update_visibility' }
  end
  resources :saas, only: :show
  resources :users, except: :show do
    collection { get 'random_token' }
  end
  resources :physical_racks, except: :show
  resources :sites, except: :show
  resources :operating_systems
  resources :tomcats, only: [:index, :show]
  resources :databases do
    collection { get 'distribution' }
    member { delete 'destroy_instance' }
  end
  resources :storages
  resources :servers do
    collection { get 'maintenance' }
  end
  resources :applications

  Dir.glob(File.expand_path("../../vendor/plugins/*/config/routes.rb",__FILE__)).each do |routefile|
    engine_name = routefile.gsub("/config/routes.rb", "").gsub(%r{.*/vendor/plugins/}, "")
    engine = "#{engine_name.camelize}::Engine".constantize rescue nil
    mount engine => "/#{engine_name}" unless engine.nil?
  end

  put 'hide_announcement' => 'javascripts#hide_announcement', as: 'hide_announcement' 

  get 'puppet(/:action(.:format))', to: 'puppet', as: 'puppet'

  root to: "welcome#index"

  match '*a', to: 'Application#render_404'

end

app/models/datacenter.rb
class Datacenter
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String

  validates_presence_of :name
  validates_uniqueness_of :name

  class << self
    def default=(datacenter)
      Thread.current[:default_datacenter] = datacenter
    end

    def default
      Thread.current[:default_datacenter] || first || create(name: "Datacenter")
    end
  end
end

app/controllers/datacenters_controller.rb
class DatacentersController < InheritedResources::Base
  layout 'admin'

  def create
    create! { datacenters_url }
  end

  def update
    update! { datacenters_url }
  end
end

app/views/datacenters/_form.html.erb
<div class="span9 center">

<%= simple_form_for(@datacenter) do |f| %>
  <%= action_links do %>
    <%= f.button :submit, class: "btn btn-primary" %>
    <%= t(:or) %> <%= link_to t(:back_to_the_list), datacenters_path %>
  <% end %>

  <table class="show_item">
    <tbody>
      <%= tabular_errors @datacenter %>
      <%= f.input :name, required: true,
                         wrapper_class: "th",
                         input_html: { size: 30 } %>
    </tbody>
  </table>
<% end %>

</div>

app/views/datacenters/edit.html.erb
<% title t(:edit_a_datacenter) %>

<%= render 'form' %>

app/views/datacenters/index.html.erb
<% title t(:datacenters) %>

<div class="span9 center">

<%= action_links do %>
  <%= link_to t(:new_datacenter), new_datacenter_path %>
<% end %>

<table class="pretty list datacenters">
<thead>
  <tr>
    <th><%= t(:name) %></th>
    <th></th>
  </tr>
</thead>
<tbody class="long-list">
<% @datacenters.each do |datacenter| %>
  <tr>
    <td><%= link_to datacenter.name, edit_datacenter_path(datacenter) %></td>
    <td><%= link_to_delete datacenter %></td>
  </tr>
<% end %>
</tbody>
</table>

</div>

app/views/datacenters/new.html.erb
<% title t(:new_datacenter) %>

<%= render 'form' %>